services:
  db_container:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - product_catalogue_network

  cache_container:
    image: redis:latest
    container_name: product_catalogue_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - product_catalogue_network

volumes:
  postgres_data:
  redis_data:

networks:
  product_catalogue_network:
    driver: bridge
