name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout  
        uses: actions/checkout@v4
        
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Format Code with Biome
        run: npx @biomejs/biome format --write ./src

      - name: Run Biome
        run: biome ci . --verbose

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
      #- run: npm test
